# Generated by Django 4.0.4 on 2022-04-28 20:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_created=True, blank=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(null=True)),
                ('could_use_in_bouquet', models.BooleanField(default=True)),
                ('Wikipedia', models.URLField(default='https://www.wikipedia.org/', unique_for_date='delivered_at')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(auto_created=True, editable=False)),
                ('second_email', models.EmailField(max_length=254)),
                ('diname', models.CharField(max_length=64)),
                ('invoice', models.FileField(upload_to='')),
                ('discount_size', models.DecimalField(blank=True, decimal_places=10, max_digits=100)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frech_period', models.DurationField(default=datetime.timedelta(days=5), help_text='Use this field wen you need to have information about bouquet fresh time')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField(default=1.0)),
                ('flowers', models.ManyToManyField(to='lesson_5.flower', verbose_name='This bouquet constants of this flowers')),
            ],
        ),
    ]
